name: 'Documentation'

on:
  workflow_call:

jobs:
  build:
    name: 'Build RST'

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Python 3.11"
        uses: "actions/setup-python@v5"
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: "Display Python version"
        run: python -c "import sys; print(sys.version)"

      - name: "Install custom requirements via pip"
        run: "pip install -r docs/requirements.txt"

      - name: "Build documentation"
        run: "sphinx-build -W -b html -d _build/doctrees docs _build/html"

  doctor-rst:
    name: 'DOCtor-RST'

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Run DOCtor-RST"
        uses: "docker://oskarstark/doctor-rst"
        with:
          args: --short --error-format=github
        env:
          DOCS_DIR: 'docs/'
